import type { NextPage } from "next";
import { useSession, signOut } from "next-auth/react";

import { requireAuth } from "@/root/common/requireAuth";
import Head from "next/head";
import CreateProject from "@/root/components/CreateProject";

const Dashboard: NextPage = () => {
  const {data} = useSession();

  return (
    <>
      <Head>
        <title>PogaDev - Dashboard</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <header>
          <h1>
            Hello, {data?.user?.name}!
          </h1>
          <button
            onClick={() => signOut({callbackUrl: "/"})}
          >
            Logout
          </button>
        </header>

        <CreateProject/>
      </main>
    </>
  );
};

export const getServerSideProps = requireAuth(async (ctx) => {
  return {props: {}};
});


export default Dashboard;