import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useCallback } from "react";
import { signIn } from "next-auth/react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";

import { loginSchema, ILogin } from "@/root/schema/user.schema";

const Home: NextPage = () => {
  const {register, handleSubmit} = useForm<ILogin>({
    resolver: zodResolver(loginSchema),
  });

  const onSubmit = useCallback(async (data: ILogin) => {
    await signIn("credentials", {...data, callbackUrl: "/"});
  }, []);

  return (
    <div>
      <Head>
        <title>Next App - Login</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main>
        <form
          onSubmit={handleSubmit(onSubmit)}
        >
          <input
            type="email"
            placeholder="Type your email..."
            {...register("email")}
          />
          <input
            type="password"
            placeholder="Type your password..."
            {...register("password")}
          />
          <div>
            <Link href="/signup" className="link">
              Go to sign up
            </Link>
            <button className="btn btn-secondary" type="submit">
              Login
            </button>
          </div>
        </form>
      </main>
    </div>
  );
};

export default Home;